# Test MDC citations harvesting code

## Import

In [1]:
%load_ext autoreload
%autoreload 2

In [3]:
from sindex.sources.mdc.jobs import build_mdc_index, find_citations_mdc_duckdb
from sindex.core.dates import get_best_dataset_date
import os
import duckdb
import pandas as df

## Paths

In [4]:
mdc_json_path = r"D:\pipeline-data\external\mdc-corpus"
db_path =r"D:\pipeline-data\external\mdc-corpus\mdc_index.duckdb"

## Build MDC DuckDB table (can skip if already done)

In [4]:
build_mdc_index(
    mdc_folder = mdc_path,
    db_path = db_path)

'input\\mdc-light\\mdc_index.duckdb'

## Check DB

In [5]:
con = duckdb.connect(db_path, read_only=True)
con.execute("SHOW TABLES").fetchall()
con.execute("DESCRIBE mdc_index").df()
display(con.execute("SELECT * FROM mdc_index LIMIT 20").df())
con.close()

,dataset_norm,citation_link,citation_date,citation_year
0,quh61239,https://doi.org/10.1016/j.jmgm.2022.108396,2023-03-01T00:00:00+00:00,2023
1,10.5517/cc69ygw,https://doi.org/10.1021/ic0255306,2002-04-30T00:00:00+00:00,2002
2,kt218684,https://doi.org/10.1186/s40249-017-0362-7,2017-10-02T00:00:00+00:00,2017
3,10.15468/dl.93n7k6,https://doi.org/10.3897/vcs.98324,2023-01-13T00:00:00+00:00,2023
4,ef486517,https://doi.org/10.1186/1471-2148-10-304,2010-10-12T00:00:00+00:00,2010
5,10.26093/cds/vizier.36590181,https://doi.org/10.1051/0004-6361/202142724,2022-03-25T00:00:00+00:00,2022
6,kf572085,https://doi.org/10.3897/zookeys.457.6569,2014-11-25T00:00:00+00:00,2014
7,prjna292902,https://doi.org/10.1016/j.chom.2019.10.022,2020-01-01T00:00:00+00:00,2020
8,t0004,https://doi.org/10.1186/s13048-022-00954-w,2022-02-08T00:00:00+00:00,2022
9,10.5517/cc8y5cq,https://doi.org/10.1021/jp047187r,2005-02-10T00:00:00+00:00,2005
10,q91y97,https://doi.org/10.3389/fpubh.2021.678856,2021-07-02T00:00:00+00:00,2021
11,2p54,https://doi.org/10.1371/journal.pone.0153427,2016-04-12T00:00:00+00:00,2016
12,a4220,https://doi.org/10.1038/s41467-019-12923-x,2019-11-06T00:00:00+00:00,2019
13,ef469662,https://doi.org/10.1371/journal.pone.0164435,2016-10-19T00:00:00+00:00,2016
14,5e2c,https://doi.org/10.3897/zookeys.1066.69697,2021-10-28T00:00:00+00:00,2021
15,c6ti90,https://doi.org/10.1038/s41477-022-01326-4,2023-01-09T00:00:00+00:00,2023
16,mn594805,https://doi.org/10.7717/peerj.15934,2023-08-28T00:00:00+00:00,2023
17,af414426,https://doi.org/10.1128/jcm.42.4.1396-1401.2004,2004-04-01T00:00:00+00:00,2004
18,err2610695,https://doi.org/10.1093/gbe/evy239,2018-12-01T00:00:00+00:00,2018
19,kf557595,https://doi.org/10.1038/srep20016,2016-01-28T00:00:00+00:00,2016

In [5]:
con = duckdb.connect(db_path, read_only=True)
display(con.execute("""
    SELECT *
    FROM mdc_index
    WHERE dataset_norm LIKE 'http%'
    LIMIT 10
""").df())
con.close()

,dataset_norm,citation_link,citation_date
0,https://osf.io/497ej,https://doi.org/10.3389/fnhum.2022.821545,2022-04-20T00:00:00+00:00
1,https://dataverse.harvard.edu/dataverse/glw_3,https://doi.org/10.1073/pnas.2121998119,2022-03-28T00:00:00+00:00
2,https://zoobank.org/5be15179-7ca0-4f3d-a475-d2...,https://doi.org/10.3897/zookeys.1111.73371,2022-07-11T00:00:00+00:00
3,https://ghdx.healthdata.org/lbd-data,https://doi.org/10.1136/bmjgh-2021-005238,2021-06-01T00:00:00+00:00
4,https://zoobank.org/8581a1b1-1cba-44c0-8b04-1d...,https://doi.org/10.3897/zookeys.741.21936,2018-03-07T00:00:00+00:00
5,https://psyarxiv.com/9d3yf/,https://doi.org/10.1002/brb3.2444,2021-12-03T00:00:00+00:00
6,https://osf.io/2e86d,https://doi.org/10.1098/rsos.170367,2017-12-06T00:00:00+00:00
7,https://osf.io/35k2w/,https://doi.org/10.1371/journal.pone.0262902,2022-01-28T00:00:00+00:00
8,https://singularityag.ch,https://doi.org/10.3390/jcm11247266,2022-12-07T00:00:00+00:00
9,https://osf.io/mkj34,https://doi.org/10.1371/journal.pone.0220509,2019-08-22T00:00:00+00:00

In [6]:
con = duckdb.connect(db_path, read_only=True)
row_count_result = con.execute("SELECT COUNT(*) FROM mdc_index").fetchone()
row_count = row_count_result[0]

print(f"The table has {row_count:,} rows.")
con.close()

The table has 9,567,909 rows.

## Find citations

### DOI

In [8]:
doi = "10.13026/kpb9-mt58"
dataset_pubyear = 2024
find_citations_mdc_duckdb(doi,dataset_pubyear = dataset_pubyear, db_path = db_path)

[{'dataset_id': '10.13026/kpb9-mt58',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.3389/fcimb.2025.1545979',
  'citation_weight': 1.23,
  'citation_date': '2025-04-17T00:00:00+00:00',
  'placeholder_date': False,
  'citation_year': 2025,
  'placeholder_year': False},
 {'dataset_id': '10.13026/kpb9-mt58',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.1002/alz.14564',
  'citation_weight': 1.23,
  'citation_date': '2025-03-29T00:00:00+00:00',
  'placeholder_date': False,
  'citation_year': 2025,
  'placeholder_year': False},
 {'dataset_id': '10.13026/kpb9-mt58',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.3389/fneur.2025.1529415',
  'citation_weight': 1.23,
  'citation_date': '2025-02-12T00:00:00+00:00',
  'placeholder_date': False,
  'citation_year': 2025,
  'placeholder_year': False},
 {'dataset_id': '10.13026/kpb9-mt58',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.1136/bmjopen-2024-087427',
  'citation_weight': 1.23,
  'citation_date': '2025-02-01T00:00:00+00:00',
  'placeholder_date': False,
  'citation_year': 2025,
  'placeholder_year': False},
 {'dataset_id': '10.13026/kpb9-mt58',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.1093/jamia/ocae303',
  'citation_weight': 1.0,
  'citation_date': '2024-12-13T00:00:00+00:00',
  'placeholder_date': False,
  'citation_year': 2024,
  'placeholder_year': False}]

In [9]:
doi = "10.13026/kpb9-mt58"
dataset_pubyear = 2027
find_citations_mdc_duckdb(doi,dataset_pubyear = dataset_pubyear, db_path = db_path)

[{'dataset_id': '10.13026/kpb9-mt58',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.3389/fcimb.2025.1545979',
  'citation_weight': 1.0,
  'citation_date': '2025-04-17T00:00:00+00:00',
  'placeholder_date': False,
  'citation_year': 2025,
  'placeholder_year': False},
 {'dataset_id': '10.13026/kpb9-mt58',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.1002/alz.14564',
  'citation_weight': 1.0,
  'citation_date': '2025-03-29T00:00:00+00:00',
  'placeholder_date': False,
  'citation_year': 2025,
  'placeholder_year': False},
 {'dataset_id': '10.13026/kpb9-mt58',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.3389/fneur.2025.1529415',
  'citation_weight': 1.0,
  'citation_date': '2025-02-12T00:00:00+00:00',
  'placeholder_date': False,
  'citation_year': 2025,
  'placeholder_year': False},
 {'dataset_id': '10.13026/kpb9-mt58',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.1136/bmjopen-2024-087427',
  'citation_weight': 1.0,
  'citation_date': '2025-02-01T00:00:00+00:00',
  'placeholder_date': False,
  'citation_year': 2025,
  'placeholder_year': False},
 {'dataset_id': '10.13026/kpb9-mt58',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.1093/jamia/ocae303',
  'citation_weight': 1.0,
  'citation_date': '2024-12-13T00:00:00+00:00',
  'placeholder_date': False,
  'citation_year': 2024,
  'placeholder_year': False}]

In [10]:
doi_url = "http://doi.org/10.13026/kpb9-mt58"
find_citations_mdc_duckdb(doi, db_path = db_path)

[{'dataset_id': '10.13026/kpb9-mt58',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.3389/fcimb.2025.1545979',
  'citation_weight': 1.0,
  'citation_date': '2025-04-17T00:00:00+00:00',
  'placeholder_date': False,
  'citation_year': 2025,
  'placeholder_year': False},
 {'dataset_id': '10.13026/kpb9-mt58',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.1002/alz.14564',
  'citation_weight': 1.0,
  'citation_date': '2025-03-29T00:00:00+00:00',
  'placeholder_date': False,
  'citation_year': 2025,
  'placeholder_year': False},
 {'dataset_id': '10.13026/kpb9-mt58',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.3389/fneur.2025.1529415',
  'citation_weight': 1.0,
  'citation_date': '2025-02-12T00:00:00+00:00',
  'placeholder_date': False,
  'citation_year': 2025,
  'placeholder_year': False},
 {'dataset_id': '10.13026/kpb9-mt58',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.1136/bmjopen-2024-087427',
  'citation_weight': 1.0,
  'citation_date': '2025-02-01T00:00:00+00:00',
  'placeholder_date': False,
  'citation_year': 2025,
  'placeholder_year': False},
 {'dataset_id': '10.13026/kpb9-mt58',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.1093/jamia/ocae303',
  'citation_weight': 1.0,
  'citation_date': '2024-12-13T00:00:00+00:00',
  'placeholder_date': False,
  'citation_year': 2024,
  'placeholder_year': False}]

In [11]:
doi = "10.5517/ccsg3t4"
dataset_pubyear  = 2010
find_citations_mdc_duckdb(doi, dataset_pubyear = dataset_pubyear, db_path = db_path)

[{'dataset_id': '10.5517/ccsg3t4',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.1038/nature09085',
  'citation_weight': 1.0,
  'citation_date': '2010-06-01T00:00:00+00:00',
  'placeholder_date': False,
  'citation_year': 2010,
  'placeholder_year': False}]

### EMDB ID

In [12]:
emdb_id = "emd-24511"
dataset_pubyear = 2021
find_citations_mdc_duckdb(emdb_id, dataset_pubyear = dataset_pubyear, db_path = db_path)

[{'dataset_id': 'emd-24511',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.1038/s41467-023-37986-9',
  'citation_weight': 1.36,
  'citation_date': '2023-04-19T00:00:00+00:00',
  'placeholder_date': False,
  'citation_year': 2023,
  'placeholder_year': False}]

In [13]:
emdb_id = "emd-2451"
dataset_pubyear = 2027
find_citations_mdc_duckdb(emdb_id, dataset_pubyear = dataset_pubyear, db_path = db_path)

[{'dataset_id': 'emd-2451',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.1038/s41594-022-00833-4',
  'citation_weight': 1.0,
  'citation_date': '2022-09-12T00:00:00+00:00',
  'placeholder_date': False,
  'citation_year': 2022,
  'placeholder_year': False},
 {'dataset_id': 'emd-2451',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.1128/jvi.01249-21',
  'citation_weight': 1.0,
  'citation_date': '2021-11-09T00:00:00+00:00',
  'placeholder_date': False,
  'citation_year': 2021,
  'placeholder_year': False},
 {'dataset_id': 'emd-2451',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.1038/nature12658',
  'citation_weight': 1.0,
  'citation_date': '2013-11-01T00:00:00+00:00',
  'placeholder_date': False,
  'citation_year': 2013,
  'placeholder_year': False},
 {'dataset_id': 'emd-2451',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.1016/j.jbc.2021.101187',
  'citation_weight': 1.0,
  'citation_date': '2021-10-01T00:00:00+00:00',
  'placeholder_date': False,
  'citation_year': 2021,
  'placeholder_year': False},
 {'dataset_id': 'emd-2451',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.7554/elife.73368',
  'citation_weight': 1.0,
  'citation_date': '2021-11-04T00:00:00+00:00',
  'placeholder_date': False,
  'citation_year': 2021,
  'placeholder_year': False},
 {'dataset_id': 'emd-2451',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.1007/s10969-014-9179-9',
  'citation_weight': 1.0,
  'citation_date': '2014-04-20T00:00:00+00:00',
  'placeholder_date': False,
  'citation_year': 2014,
  'placeholder_year': False},
 {'dataset_id': 'emd-2451',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.1038/nsmb.2736',
  'citation_weight': 1.0,
  'citation_date': '2013-12-15T00:00:00+00:00',
  'placeholder_date': False,
  'citation_year': 2013,
  'placeholder_year': False}]

In [14]:
emdb_id = "EMD-2451"
dataset_pubyear = 2013
find_citations_mdc_duckdb(emdb_id, dataset_pubyear = dataset_pubyear, db_path = db_path)

[{'dataset_id': 'EMD-2451',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.1038/s41594-022-00833-4',
  'citation_weight': 1.76,
  'citation_date': '2022-09-12T00:00:00+00:00',
  'placeholder_date': False,
  'citation_year': 2022,
  'placeholder_year': False},
 {'dataset_id': 'EMD-2451',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.1128/jvi.01249-21',
  'citation_weight': 1.73,
  'citation_date': '2021-11-09T00:00:00+00:00',
  'placeholder_date': False,
  'citation_year': 2021,
  'placeholder_year': False},
 {'dataset_id': 'EMD-2451',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.1038/nature12658',
  'citation_weight': 1.0,
  'citation_date': '2013-11-01T00:00:00+00:00',
  'placeholder_date': False,
  'citation_year': 2013,
  'placeholder_year': False},
 {'dataset_id': 'EMD-2451',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.1016/j.jbc.2021.101187',
  'citation_weight': 1.73,
  'citation_date': '2021-10-01T00:00:00+00:00',
  'placeholder_date': False,
  'citation_year': 2021,
  'placeholder_year': False},
 {'dataset_id': 'EMD-2451',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.7554/elife.73368',
  'citation_weight': 1.73,
  'citation_date': '2021-11-04T00:00:00+00:00',
  'placeholder_date': False,
  'citation_year': 2021,
  'placeholder_year': False},
 {'dataset_id': 'EMD-2451',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.1007/s10969-014-9179-9',
  'citation_weight': 1.23,
  'citation_date': '2014-04-20T00:00:00+00:00',
  'placeholder_date': False,
  'citation_year': 2014,
  'placeholder_year': False},
 {'dataset_id': 'EMD-2451',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.1038/nsmb.2736',
  'citation_weight': 1.0,
  'citation_date': '2013-12-15T00:00:00+00:00',
  'placeholder_date': False,
  'citation_year': 2013,
  'placeholder_year': False}]

In [15]:
url = "https://ghdx.healthdata.org/lbd-data"
find_citations_mdc_duckdb(url, db_path = db_path)

[{'dataset_id': 'https://ghdx.healthdata.org/lbd-data',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.1136/bmjgh-2021-005238',
  'citation_weight': 1.0,
  'citation_date': '2021-06-01T00:00:00+00:00',
  'placeholder_date': False,
  'citation_year': 2021,
  'placeholder_year': False}]