# Test MDC citations harvesting code

## Import

In [1]:
from sindex.sources.mdc.jobs import build_mdc_index, find_citations_mdc_duckdb
import os
import duckdb
import pandas as df

## Paths

In [2]:
current_dir = os.getcwd()
parent_dir = os.path.abspath(os.path.join(current_dir, os.pardir))
mdc_path = os.path.join(parent_dir, "input", "mdc")
#mdc_path = r"input\mdc-light"
db_path = os.path.join(mdc_path, "mdc_index.duckdb")
print(mdc_path, db_path)

C:\Users\Admin\Documents\GitHub\sindex-pipeline\input\mdc C:\Users\Admin\Documents\GitHub\sindex-pipeline\input\mdc\mdc_index.duckdb

## Build MDC DuckDB table (already done can skip)

In [4]:
build_mdc_index(
    mdc_folder = mdc_path,
    db_path = db_path)

'input\\mdc-light\\mdc_index.duckdb'

## Check DB

In [3]:
con = duckdb.connect(db_path, read_only=True)

con.execute("SHOW TABLES").fetchall()
con.execute("DESCRIBE mdc_index").df()
con.execute("SELECT * FROM mdc_index LIMIT 20").df()

,dataset_norm,citation_link,citation_date
0,10.5517/ccdc.csd.cc1nw3zm,https://doi.org/10.1021/jacs.8b13471,2019-02-27T00:00:00+00:00
1,cp006798,https://doi.org/10.1128/aac.00310-15,2015-06-01T00:00:00+00:00
2,kx128923,https://doi.org/10.1371/journal.pone.0178180,2017-07-26T00:00:00+00:00
3,kt258874,https://doi.org/10.1093/jxb/erw273,2016-08-19T00:00:00+00:00
4,10.17182/hepdata.12254.v1/t52,https://doi.org/10.1103/physrevc.73.045205,2006-04-10T00:00:00+00:00
5,cd009103,https://doi.org/10.1186/s12872-015-0115-0,2015-10-14T00:00:00+00:00
6,gse47753,https://doi.org/10.1093/nar/gkz716,2019-11-04T00:00:00+00:00
7,dq018097,https://doi.org/10.3390/jof8111200,2022-11-14T00:00:00+00:00
8,2qsh,https://doi.org/10.1080/07391102.2023.2177349,2023-03-08T00:00:00+00:00
9,p02746,https://doi.org/10.1167/iovs.10-5531,2010-10-01T00:00:00+00:00
10,nm_001009327,https://doi.org/10.1186/s13567-018-0504-3,2018-01-24T00:00:00+00:00
11,10.5517/ccdc.csd.cc279pmw,https://doi.org/10.1039/d1cc01505b,2021-01-01T00:00:00+00:00
12,nm_019677,https://doi.org/10.1371/journal.pone.0017676,2011-03-03T00:00:00+00:00
13,hc200755,https://doi.org/10.3390/microorganisms9071440,2021-07-03T00:00:00+00:00
14,1sre,https://doi.org/10.1186/s13065-018-0475-5,2018-10-22T00:00:00+00:00
15,10.6084/m9.figshare.7409156.v1,https://doi.org/10.1186/s12943-018-0912-z,2018-11-30T00:00:00+00:00
16,ai356398,https://doi.org/10.1007/s00018-009-0222-0,2009-12-15T00:00:00+00:00
17,5jjr,https://doi.org/10.3390/v13060956,2021-05-21T00:00:00+00:00
18,5ds3,https://doi.org/10.3390/ijms25084529,2024-04-20T00:00:00+00:00
19,ef124613,https://doi.org/10.1002/mbo3.1060,2020-05-28T00:00:00+00:00

In [4]:
con.execute("""
    SELECT *
    FROM mdc_index
    WHERE dataset_norm LIKE 'http%'
    LIMIT 10
""").df()

,dataset_norm,citation_link,citation_date
0,https://osf.io/497ej,https://doi.org/10.3389/fnhum.2022.821545,2022-04-20T00:00:00+00:00
1,https://dataverse.harvard.edu/dataverse/glw_3,https://doi.org/10.1073/pnas.2121998119,2022-03-28T00:00:00+00:00
2,https://zoobank.org/5be15179-7ca0-4f3d-a475-d2...,https://doi.org/10.3897/zookeys.1111.73371,2022-07-11T00:00:00+00:00
3,https://ghdx.healthdata.org/lbd-data,https://doi.org/10.1136/bmjgh-2021-005238,2021-06-01T00:00:00+00:00
4,https://zoobank.org/8581a1b1-1cba-44c0-8b04-1d...,https://doi.org/10.3897/zookeys.741.21936,2018-03-07T00:00:00+00:00
5,https://psyarxiv.com/9d3yf/,https://doi.org/10.1002/brb3.2444,2021-12-03T00:00:00+00:00
6,https://osf.io/2e86d,https://doi.org/10.1098/rsos.170367,2017-12-06T00:00:00+00:00
7,https://osf.io/35k2w/,https://doi.org/10.1371/journal.pone.0262902,2022-01-28T00:00:00+00:00
8,https://singularityag.ch,https://doi.org/10.3390/jcm11247266,2022-12-07T00:00:00+00:00
9,https://osf.io/mkj34,https://doi.org/10.1371/journal.pone.0220509,2019-08-22T00:00:00+00:00

In [14]:
row_count_result = con.execute("SELECT COUNT(*) FROM mdc_index").fetchone()
row_count = row_count_result[0]

print(f"The table has {row_count} rows.")

The table has 9567909 rows.

## Find citations

### DOI

In [5]:
doi = "10.13026/kpb9-mt58"
dataset_pub_date = "2024-10-10T21:27:19+00:00"

In [6]:
find_citations_mdc_duckdb(doi, dataset_pub_date = dataset_pub_date, db_path = db_path)

[{'dataset_id': '10.13026/kpb9-mt58',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.1136/bmjopen-2024-087427',
  'citation_weight': 1.09,
  'citation_date': '2025-02-01T00:00:00+00:00'},
 {'dataset_id': '10.13026/kpb9-mt58',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.3389/fcimb.2025.1545979',
  'citation_weight': 1.14,
  'citation_date': '2025-04-17T00:00:00+00:00'},
 {'dataset_id': '10.13026/kpb9-mt58',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.1002/alz.14564',
  'citation_weight': 1.13,
  'citation_date': '2025-03-29T00:00:00+00:00'},
 {'dataset_id': '10.13026/kpb9-mt58',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.3389/fneur.2025.1529415',
  'citation_weight': 1.1,
  'citation_date': '2025-02-12T00:00:00+00:00'},
 {'dataset_id': '10.13026/kpb9-mt58',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.1093/jamia/ocae303',
  'citation_weight': 1.05,
  'citation_date': '2024-12-13T00:00:00+00:00'}]

In [7]:
doi_url = "http://doi.org/10.13026/kpb9-mt58"
find_citations_mdc_duckdb(doi, db_path = db_path)

[{'dataset_id': '10.13026/kpb9-mt58',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.1136/bmjopen-2024-087427',
  'citation_weight': 1.0,
  'citation_date': '2025-02-01T00:00:00+00:00'},
 {'dataset_id': '10.13026/kpb9-mt58',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.3389/fcimb.2025.1545979',
  'citation_weight': 1.0,
  'citation_date': '2025-04-17T00:00:00+00:00'},
 {'dataset_id': '10.13026/kpb9-mt58',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.1002/alz.14564',
  'citation_weight': 1.0,
  'citation_date': '2025-03-29T00:00:00+00:00'},
 {'dataset_id': '10.13026/kpb9-mt58',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.3389/fneur.2025.1529415',
  'citation_weight': 1.0,
  'citation_date': '2025-02-12T00:00:00+00:00'},
 {'dataset_id': '10.13026/kpb9-mt58',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.1093/jamia/ocae303',
  'citation_weight': 1.0,
  'citation_date': '2024-12-13T00:00:00+00:00'}]

### EMDB ID

In [8]:
emdb_id = "emd-2451"
dataset_pub_date = "2014-01-10T21:27:19+00:00"

In [9]:
find_citations_mdc_duckdb(emdb_id, dataset_pub_date = dataset_pub_date, db_path = db_path)

[{'dataset_id': 'emd-2451',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.1038/s41594-022-00833-4',
  'citation_weight': 1.75,
  'citation_date': '2022-09-12T00:00:00+00:00'},
 {'dataset_id': 'emd-2451',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.1128/jvi.01249-21',
  'citation_weight': 1.72,
  'citation_date': '2021-11-09T00:00:00+00:00'},
 {'dataset_id': 'emd-2451',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.7554/elife.73368',
  'citation_weight': 1.72,
  'citation_date': '2021-11-04T00:00:00+00:00'},
 {'dataset_id': 'emd-2451',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.1016/j.jbc.2021.101187',
  'citation_weight': 1.71,
  'citation_date': '2021-10-01T00:00:00+00:00'},
 {'dataset_id': 'emd-2451',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.1007/s10969-014-9179-9',
  'citation_weight': 1.08,
  'citation_date': '2014-04-20T00:00:00+00:00'},
 {'dataset_id': 'emd-2451',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.1038/nsmb.2736',
  'citation_weight': 1.0,
  'citation_date': '2013-12-15T00:00:00+00:00'},
 {'dataset_id': 'emd-2451',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.1038/nature12658',
  'citation_weight': 1.0,
  'citation_date': '2013-11-01T00:00:00+00:00'}]

In [20]:
emdb_id = "EMD-2451"
find_citations_mdc_duckdb(emdb_id, dataset_pub_date = dataset_pub_date, db_path = db_path)

[{'dataset_id': 'EMD-2451',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.1038/s41594-022-00833-4',
  'citation_weight': 1.75,
  'citation_date': '2022-09-12T00:00:00+00:00'},
 {'dataset_id': 'EMD-2451',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.1128/jvi.01249-21',
  'citation_weight': 1.72,
  'citation_date': '2021-11-09T00:00:00+00:00'},
 {'dataset_id': 'EMD-2451',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.7554/elife.73368',
  'citation_weight': 1.72,
  'citation_date': '2021-11-04T00:00:00+00:00'},
 {'dataset_id': 'EMD-2451',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.1016/j.jbc.2021.101187',
  'citation_weight': 1.71,
  'citation_date': '2021-10-01T00:00:00+00:00'},
 {'dataset_id': 'EMD-2451',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.1007/s10969-014-9179-9',
  'citation_weight': 1.08,
  'citation_date': '2014-04-20T00:00:00+00:00'},
 {'dataset_id': 'EMD-2451',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.1038/nsmb.2736',
  'citation_weight': 1.0,
  'citation_date': '2013-12-15T00:00:00+00:00'},
 {'dataset_id': 'EMD-2451',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.1038/nature12658',
  'citation_weight': 1.0,
  'citation_date': '2013-11-01T00:00:00+00:00'}]

In [11]:
url = "https://ghdx.healthdata.org/lbd-data"
find_citations_mdc_duckdb(url, db_path = db_path)

[{'dataset_id': 'https://ghdx.healthdata.org/lbd-data',
  'source': ['mdc'],
  'citation_link': 'https://doi.org/10.1136/bmjgh-2021-005238',
  'citation_weight': 1.0,
  'citation_date': '2021-06-01T00:00:00+00:00'}]