In [47]:
%load_ext autoreload
%autoreload 2
from sindex.sources.openalex.snapshot import (
    run_openalex_sweep, 
    process_openalex_topics_for_dois, 
    process_openalex_citations_for_dois,
    create_citation_weights_table,
)
import duckdb
import os

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

## Test with some files from the snapshot

In [16]:
# Path configuration
config = {
    "source_dir": r"E:\OpenAlex\snapshot-light\data\works",
    "meta_out": r"C:\Users\Admin\Documents\OpenAlex\test\metadata",
    "cite_out": r"C:\Users\Admin\Documents\OpenAlex\test\citations",
     "db_path": r"C:\Users\Admin\Documents\OpenAlex\test\openalex_test.db",
    "temp": r"C:\Users\Admin\Documents\OpenAlex\test\duckdb_temp",
}

In [4]:
# Create parquet filesfrom oa works gz files
results = run_openalex_sweep(**config, max_workers=16)

if results['errors']:
    print(f"\nCompleted with errors: {len(results['errors'])}")

Syncing 13 files...
Progress: 13/13 (New: 0, Skipped: 13)

In [5]:
# Load in DuckDB
db_path = r"C:\Users\Admin\Documents\OpenAlex\test\openalex_test.db"
con = duckdb.connect(db_path)

meta_path = f"{config['meta_out']}/*.parquet"
cite_path = f"{config['cite_out']}/*.parquet"

con.execute(f"CREATE OR REPLACE TABLE works AS SELECT * FROM read_parquet('{meta_path}')")
con.execute(f"CREATE OR REPLACE TABLE citations AS SELECT * FROM read_parquet('{cite_path}')")

meta_count = con.execute("SELECT count(*) FROM works").fetchone()[0]
cite_count = con.execute("SELECT count(*) FROM citations").fetchone()[0]

print(f"Success! Loaded {meta_count:,} works and {cite_count:,} citation links.")

Loading metadata from: C:\Users\Admin\Documents\OpenAlex\test\metadata/*.parquet
Loading citations from: C:\Users\Admin\Documents\OpenAlex\test\citations/*.parquet
Success! Loaded 408 works and 689 citation links.

In [18]:
# Preview
df_sample_work = con.execute("SELECT * FROM works ORDER BY topic_id DESC LIMIT 10").df()
display(df_sample_work)
df_sample_citations = con.execute("SELECT * FROM citations ORDER BY citing_oa_id LIMIT 20").df()
display(df_sample_citations)

,oa_id,doi,pub_date,topic_id,topic_name,topic_score
0,W1547878197,10.18372/2411-264x.3.2141,2012-09-10,T13497,Hermeneutics and Narrative Identity,0.9879
1,W2288414950,10.36418/syntax-literate.v3i3.350,2018-03-27,T13497,Hermeneutics and Narrative Identity,0.9879
2,W1843317143,10.31941/delta.v1i2.482,2017-08-30,T13497,Hermeneutics and Narrative Identity,0.9879
3,W2338400371,10.11903/1002.6495.2014.087,2015-02-14,T13497,Hermeneutics and Narrative Identity,0.9879
4,W2281025132,10.18372/2412-2157.12.8295,2015-05-23,T13497,Hermeneutics and Narrative Identity,0.9879
5,W2283374966,10.2495/str030361,2003-04-10,T13497,Hermeneutics and Narrative Identity,0.9879
6,W2328865013,,1977-01-01,T13497,Hermeneutics and Narrative Identity,0.9879
7,W2303842597,,1986-02-01,T13497,Hermeneutics and Narrative Identity,0.9879
8,W2395157951,10.33772/medula.v1i1.188,2013-01-01,T13497,Hermeneutics and Narrative Identity,0.9879
9,W2190023776,10.18372/2412-2157.16.9474,2015-11-16,T13497,Hermeneutics and Narrative Identity,0.9879

   citing_oa_id  cited_oa_id
0    W139517439  W2114449116
1    W144694350    W40440957
2   W1480302865  W1966463595
3   W1480302865  W2271065608
4   W1480302865  W2236238848
5   W1480302865  W2073521201
6   W1480302865  W2338124369
7   W1480302865  W2292183954
8   W1480302865  W2044284902
9   W1480302865  W2005121720
10  W1507469036   W207408070
11  W1507469036  W2070317712
12  W1507469036  W2030551085
13  W1507469036  W1978489019
14  W1507469036  W1966574389
15  W1507469036  W1964955172
16  W1507469036  W2087782651
17  W1507469036  W2021223631
18  W1507469036  W2117418442
19  W1507469036  W2152852772

In [19]:
target_doi = "10.11903/1002.6495.2014.087"

query = f"""
SELECT 
    -- 1. Info about the Target Paper
    w.doi AS target_doi,
    w.topic_name AS target_topic,
    w.pub_date AS target_date,
    
    -- 2. Info about the Citing Papers
    c.citing_oa_id,
    citing_meta.doi AS citing_doi,
    citing_meta.pub_date AS citing_date,
    citing_meta.topic_name AS citing_topic
FROM works w
LEFT JOIN citations c ON w.oa_id = c.cited_oa_id
LEFT JOIN works citing_meta ON c.citing_oa_id = citing_meta.oa_id
WHERE w.doi = '{target_doi}';
"""

df_results = con.execute(query).df()
display(df_results)

,target_doi,target_topic,target_date,citing_oa_id,citing_doi,citing_date,citing_topic
0,10.11903/1002.6495.2014.087,Hermeneutics and Narrative Identity,2015-02-14,None,None,None,None

In [18]:
doi_list = ['10.18372/2411-264x.3.2141', '10.36418/syntax-literate.v3i3.350']

# Connect to DuckDB (creates a file named my_data.db)
con = duckdb.connect(config["db_path"])

# Create the table using the Python list
con.execute("CREATE TABLE target_dois AS SELECT * FROM (SELECT unnest(?) AS doi)", [doi_list])

# Verify
display(con.execute("SELECT * FROM target_dois").df())

                                 doi
0          10.18372/2411-264x.3.2141
1  10.36418/syntax-literate.v3i3.350

In [19]:
process_openalex_topics_for_dois(
    db_path=config["db_path"], 
    meta_folder=config["meta_out"], 
    mem_limit="32GB", 
    temp_dir=config["temp"]
)

Starting scan of 13 metadata files...
Scanned: 13/13 | Elapsed: 00:00
Finalizing: Deduplicating DOIs (keeping highest topic scores)...
Done! Unique datasets found: 2 | Total Time: 0.01 min

In [20]:
display(con.execute("SELECT * FROM my_datasets_topics").df())

,oa_id,doi,pub_date,topic_id,topic_name,topic_score
0,W1547878197,10.18372/2411-264x.3.2141,2012-09-10,T13497,Hermeneutics and Narrative Identity,0.9879
1,W2288414950,10.36418/syntax-literate.v3i3.350,2018-03-27,T13497,Hermeneutics and Narrative Identity,0.9879

In [21]:
con.close()

## Actual run full OpenAlex snapshot

### Extract topics nd citations in parquet files

In [39]:
# Path configuration
config = {
    "source_dir": r"E:\OpenAlex\openalex-snapshot\data\works",
    "meta_out": r"C:\Users\Admin\Documents\OpenAlex\full-snapshot\metadata",
    "cite_out": r"C:\Users\Admin\Documents\OpenAlex\full-snapshot\citations",
    "db_path": r"C:\Users\Admin\Documents\OpenAlex\openalex-snapshot\openalex.db",
    "temp": r"C:/Users/Admin/Documents/OpenAlex/openalex-snapshot/duckdb_temp",
}

In [21]:
# Create parquet files from oa works gz files
results = run_openalex_sweep(**config, max_workers=16)

if results['errors']:
    print(f"\nCompleted with errors: {len(results['errors'])}")

Syncing 1716 files...
Progress: 1716/1716 (New: 1716, Skipped: 0)

### Get topics

In [24]:
process_openalex_topics_for_dois(
    db_path=config["db_path"], 
    meta_folder=config["meta_out"], 
    mem_limit="32GB", 
    temp_dir=config["temp"]
)

Starting scan of 1716 metadata files...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 757/1716 | Elapsed: 12:33

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 767/1716 | Elapsed: 12:54

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 773/1716 | Elapsed: 13:06

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 777/1716 | Elapsed: 13:15

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 778/1716 | Elapsed: 13:17

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 780/1716 | Elapsed: 13:21

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 784/1716 | Elapsed: 13:30

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 786/1716 | Elapsed: 13:34

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 789/1716 | Elapsed: 13:41

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 791/1716 | Elapsed: 13:45

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 792/1716 | Elapsed: 13:47

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 793/1716 | Elapsed: 13:49

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 794/1716 | Elapsed: 13:52

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 795/1716 | Elapsed: 13:54

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 796/1716 | Elapsed: 13:56

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 797/1716 | Elapsed: 13:58

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 798/1716 | Elapsed: 14:01

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 799/1716 | Elapsed: 14:03

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 800/1716 | Elapsed: 14:05

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 801/1716 | Elapsed: 14:09

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 802/1716 | Elapsed: 14:11

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 803/1716 | Elapsed: 14:14

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 804/1716 | Elapsed: 14:16

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 806/1716 | Elapsed: 14:20

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 809/1716 | Elapsed: 14:26

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 810/1716 | Elapsed: 14:29

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 811/1716 | Elapsed: 14:33

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 813/1716 | Elapsed: 14:37

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 814/1716 | Elapsed: 14:39

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 815/1716 | Elapsed: 14:41

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 816/1716 | Elapsed: 14:44

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 817/1716 | Elapsed: 14:46

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 818/1716 | Elapsed: 14:48

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 819/1716 | Elapsed: 14:50

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 821/1716 | Elapsed: 14:55

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 823/1716 | Elapsed: 14:59

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 824/1716 | Elapsed: 15:01

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 825/1716 | Elapsed: 15:04

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 826/1716 | Elapsed: 15:06

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 827/1716 | Elapsed: 15:09

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 828/1716 | Elapsed: 15:11

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 829/1716 | Elapsed: 15:13

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 830/1716 | Elapsed: 15:15

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 831/1716 | Elapsed: 15:18

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 832/1716 | Elapsed: 15:20

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 833/1716 | Elapsed: 15:22

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 835/1716 | Elapsed: 15:27

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 836/1716 | Elapsed: 15:30

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 837/1716 | Elapsed: 15:32

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 838/1716 | Elapsed: 15:34

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 839/1716 | Elapsed: 15:36

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 840/1716 | Elapsed: 15:38

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 841/1716 | Elapsed: 15:41

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 842/1716 | Elapsed: 15:44

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 843/1716 | Elapsed: 15:46

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 844/1716 | Elapsed: 15:48

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 845/1716 | Elapsed: 15:50

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 846/1716 | Elapsed: 15:53

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 847/1716 | Elapsed: 15:55

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 848/1716 | Elapsed: 15:58

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 849/1716 | Elapsed: 16:00

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 850/1716 | Elapsed: 16:03

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 851/1716 | Elapsed: 16:05

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 852/1716 | Elapsed: 16:07

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 853/1716 | Elapsed: 16:09

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 854/1716 | Elapsed: 16:12

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 855/1716 | Elapsed: 16:14

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 856/1716 | Elapsed: 16:16

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 857/1716 | Elapsed: 16:19

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 858/1716 | Elapsed: 16:21

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 859/1716 | Elapsed: 16:23

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 860/1716 | Elapsed: 16:26

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 861/1716 | Elapsed: 16:29

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 862/1716 | Elapsed: 16:32

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 864/1716 | Elapsed: 16:37

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 865/1716 | Elapsed: 16:39

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 866/1716 | Elapsed: 16:41

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 867/1716 | Elapsed: 16:44

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 868/1716 | Elapsed: 16:46

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 869/1716 | Elapsed: 16:49

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 870/1716 | Elapsed: 16:52

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 871/1716 | Elapsed: 16:54

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 872/1716 | Elapsed: 16:56

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 873/1716 | Elapsed: 16:59

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 874/1716 | Elapsed: 17:01

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 876/1716 | Elapsed: 17:06

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 877/1716 | Elapsed: 17:08

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 878/1716 | Elapsed: 17:10

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 879/1716 | Elapsed: 17:12

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 880/1716 | Elapsed: 17:15

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 881/1716 | Elapsed: 17:17

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 882/1716 | Elapsed: 17:19

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 883/1716 | Elapsed: 17:22

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 884/1716 | Elapsed: 17:25

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 885/1716 | Elapsed: 17:27

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 886/1716 | Elapsed: 17:29

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 887/1716 | Elapsed: 17:32

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 888/1716 | Elapsed: 17:34

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 889/1716 | Elapsed: 17:36

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 890/1716 | Elapsed: 17:40

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 891/1716 | Elapsed: 17:42

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 892/1716 | Elapsed: 17:44

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 893/1716 | Elapsed: 17:47

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 894/1716 | Elapsed: 17:49

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 895/1716 | Elapsed: 17:52

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 896/1716 | Elapsed: 17:54

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 897/1716 | Elapsed: 17:57

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 898/1716 | Elapsed: 17:59

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 899/1716 | Elapsed: 18:01

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 900/1716 | Elapsed: 18:04

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 901/1716 | Elapsed: 18:06

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 902/1716 | Elapsed: 18:09

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 903/1716 | Elapsed: 18:11

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 904/1716 | Elapsed: 18:15

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 905/1716 | Elapsed: 18:17

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 906/1716 | Elapsed: 18:19

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 907/1716 | Elapsed: 18:22

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 908/1716 | Elapsed: 18:24

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 909/1716 | Elapsed: 18:27

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 910/1716 | Elapsed: 18:30

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 911/1716 | Elapsed: 18:33

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 912/1716 | Elapsed: 18:35

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 913/1716 | Elapsed: 18:37

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 914/1716 | Elapsed: 18:40

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 915/1716 | Elapsed: 18:42

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 916/1716 | Elapsed: 18:45

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 917/1716 | Elapsed: 18:47

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 918/1716 | Elapsed: 18:50

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 919/1716 | Elapsed: 18:52

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 920/1716 | Elapsed: 18:54

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 921/1716 | Elapsed: 18:57

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 922/1716 | Elapsed: 19:00

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 923/1716 | Elapsed: 19:02

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 924/1716 | Elapsed: 19:05

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 925/1716 | Elapsed: 19:07

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 926/1716 | Elapsed: 19:09

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 927/1716 | Elapsed: 19:12

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 928/1716 | Elapsed: 19:14

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 929/1716 | Elapsed: 19:17

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 930/1716 | Elapsed: 19:20

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 931/1716 | Elapsed: 19:22

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 932/1716 | Elapsed: 19:25

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 933/1716 | Elapsed: 19:27

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 934/1716 | Elapsed: 19:29

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 935/1716 | Elapsed: 19:32

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 936/1716 | Elapsed: 19:35

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 937/1716 | Elapsed: 19:37

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 938/1716 | Elapsed: 19:40

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 939/1716 | Elapsed: 19:42

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 940/1716 | Elapsed: 19:45

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 941/1716 | Elapsed: 19:48

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 942/1716 | Elapsed: 19:51

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 943/1716 | Elapsed: 19:53

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 944/1716 | Elapsed: 19:56

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 945/1716 | Elapsed: 19:58

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 946/1716 | Elapsed: 20:01

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 947/1716 | Elapsed: 20:04

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 948/1716 | Elapsed: 20:06

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 949/1716 | Elapsed: 20:09

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 950/1716 | Elapsed: 20:12

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 951/1716 | Elapsed: 20:14

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 952/1716 | Elapsed: 20:16

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 953/1716 | Elapsed: 20:19

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 954/1716 | Elapsed: 20:22

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 955/1716 | Elapsed: 20:24

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 956/1716 | Elapsed: 20:27

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 957/1716 | Elapsed: 20:30

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 958/1716 | Elapsed: 20:32

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 959/1716 | Elapsed: 20:35

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 960/1716 | Elapsed: 20:37

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 961/1716 | Elapsed: 20:40

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 962/1716 | Elapsed: 20:43

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 963/1716 | Elapsed: 20:46

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 964/1716 | Elapsed: 20:48

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 965/1716 | Elapsed: 20:51

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 966/1716 | Elapsed: 20:53

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 967/1716 | Elapsed: 20:56

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 968/1716 | Elapsed: 20:59

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 969/1716 | Elapsed: 21:02

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 970/1716 | Elapsed: 21:05

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 971/1716 | Elapsed: 21:08

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 972/1716 | Elapsed: 21:11

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 973/1716 | Elapsed: 21:13

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 974/1716 | Elapsed: 21:16

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 975/1716 | Elapsed: 21:18

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 976/1716 | Elapsed: 21:21

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 977/1716 | Elapsed: 21:24

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 978/1716 | Elapsed: 21:27

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 979/1716 | Elapsed: 21:29

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 980/1716 | Elapsed: 21:32

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 981/1716 | Elapsed: 21:35

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 982/1716 | Elapsed: 21:37

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 983/1716 | Elapsed: 21:40

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 984/1716 | Elapsed: 21:43

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 985/1716 | Elapsed: 21:46

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 986/1716 | Elapsed: 21:49

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 987/1716 | Elapsed: 21:51

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 988/1716 | Elapsed: 21:54

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 989/1716 | Elapsed: 21:57

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 990/1716 | Elapsed: 21:59

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 991/1716 | Elapsed: 22:03

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 992/1716 | Elapsed: 22:05

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 993/1716 | Elapsed: 22:08

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 994/1716 | Elapsed: 22:11

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 995/1716 | Elapsed: 22:14

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 996/1716 | Elapsed: 22:16

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 997/1716 | Elapsed: 22:19

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 998/1716 | Elapsed: 22:22

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 999/1716 | Elapsed: 22:25

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1000/1716 | Elapsed: 22:27

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1001/1716 | Elapsed: 22:30

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1002/1716 | Elapsed: 22:33

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1003/1716 | Elapsed: 22:36

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1004/1716 | Elapsed: 22:39

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1005/1716 | Elapsed: 22:42

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1006/1716 | Elapsed: 22:44

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1007/1716 | Elapsed: 22:47

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1008/1716 | Elapsed: 22:50

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1009/1716 | Elapsed: 22:53

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1010/1716 | Elapsed: 22:56

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1011/1716 | Elapsed: 22:59

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1012/1716 | Elapsed: 23:02

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1013/1716 | Elapsed: 23:05

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1014/1716 | Elapsed: 23:07

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1015/1716 | Elapsed: 23:10

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1016/1716 | Elapsed: 23:13

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1017/1716 | Elapsed: 23:16

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1018/1716 | Elapsed: 23:19

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1019/1716 | Elapsed: 23:22

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1020/1716 | Elapsed: 23:25

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1021/1716 | Elapsed: 23:28

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1022/1716 | Elapsed: 23:31

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1023/1716 | Elapsed: 23:33

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1024/1716 | Elapsed: 23:36

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1025/1716 | Elapsed: 23:40

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1026/1716 | Elapsed: 23:43

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1027/1716 | Elapsed: 23:46

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1028/1716 | Elapsed: 23:49

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1029/1716 | Elapsed: 23:52

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1030/1716 | Elapsed: 23:54

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1031/1716 | Elapsed: 23:57

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1032/1716 | Elapsed: 24:01

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1033/1716 | Elapsed: 24:04

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1034/1716 | Elapsed: 24:07

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1035/1716 | Elapsed: 24:10

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1036/1716 | Elapsed: 24:13

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1037/1716 | Elapsed: 24:16

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1038/1716 | Elapsed: 24:18

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1039/1716 | Elapsed: 24:22

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1040/1716 | Elapsed: 24:24

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1041/1716 | Elapsed: 24:27

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1042/1716 | Elapsed: 24:30

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1043/1716 | Elapsed: 24:33

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1044/1716 | Elapsed: 24:36

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1045/1716 | Elapsed: 24:39

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1046/1716 | Elapsed: 24:43

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1047/1716 | Elapsed: 24:46

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1048/1716 | Elapsed: 24:49

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1049/1716 | Elapsed: 24:52

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1050/1716 | Elapsed: 24:55

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1051/1716 | Elapsed: 24:58

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1052/1716 | Elapsed: 25:02

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1053/1716 | Elapsed: 25:05

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1054/1716 | Elapsed: 25:08

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1055/1716 | Elapsed: 25:11

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1056/1716 | Elapsed: 25:15

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1057/1716 | Elapsed: 25:18

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1058/1716 | Elapsed: 25:21

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1059/1716 | Elapsed: 25:24

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1060/1716 | Elapsed: 25:28

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1061/1716 | Elapsed: 25:31

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1062/1716 | Elapsed: 25:34

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1063/1716 | Elapsed: 25:38

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1064/1716 | Elapsed: 25:41

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1065/1716 | Elapsed: 25:44

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1066/1716 | Elapsed: 25:48

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1067/1716 | Elapsed: 25:51

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1068/1716 | Elapsed: 25:55

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1069/1716 | Elapsed: 25:58

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1070/1716 | Elapsed: 26:01

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1071/1716 | Elapsed: 26:04

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1072/1716 | Elapsed: 26:07

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1073/1716 | Elapsed: 26:11

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1074/1716 | Elapsed: 26:14

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1075/1716 | Elapsed: 26:17

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1076/1716 | Elapsed: 26:20

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1077/1716 | Elapsed: 26:23

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1078/1716 | Elapsed: 26:27

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1079/1716 | Elapsed: 26:30

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1080/1716 | Elapsed: 26:34

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1081/1716 | Elapsed: 26:37

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1082/1716 | Elapsed: 26:40

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1083/1716 | Elapsed: 26:44

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1084/1716 | Elapsed: 26:47

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1085/1716 | Elapsed: 26:50

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1086/1716 | Elapsed: 26:54

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1087/1716 | Elapsed: 26:58

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1088/1716 | Elapsed: 27:01

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1089/1716 | Elapsed: 27:04

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1090/1716 | Elapsed: 27:08

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1091/1716 | Elapsed: 27:11

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1092/1716 | Elapsed: 27:15

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1093/1716 | Elapsed: 27:18

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1094/1716 | Elapsed: 27:22

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1095/1716 | Elapsed: 27:25

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1096/1716 | Elapsed: 27:29

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1097/1716 | Elapsed: 27:32

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1098/1716 | Elapsed: 27:35

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1099/1716 | Elapsed: 27:39

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1100/1716 | Elapsed: 27:42

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1101/1716 | Elapsed: 27:46

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1102/1716 | Elapsed: 27:50

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1103/1716 | Elapsed: 27:53

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1104/1716 | Elapsed: 27:56

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1105/1716 | Elapsed: 28:00

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1106/1716 | Elapsed: 28:03

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1107/1716 | Elapsed: 28:07

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1108/1716 | Elapsed: 28:11

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1109/1716 | Elapsed: 28:15

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1110/1716 | Elapsed: 28:18

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1111/1716 | Elapsed: 28:21

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1112/1716 | Elapsed: 28:24

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1113/1716 | Elapsed: 28:28

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1114/1716 | Elapsed: 28:31

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1115/1716 | Elapsed: 28:36

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1116/1716 | Elapsed: 28:40

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1117/1716 | Elapsed: 28:43

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1118/1716 | Elapsed: 28:47

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1119/1716 | Elapsed: 28:50

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1120/1716 | Elapsed: 28:54

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1121/1716 | Elapsed: 28:57

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1122/1716 | Elapsed: 29:01

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1123/1716 | Elapsed: 29:05

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1124/1716 | Elapsed: 29:08

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1125/1716 | Elapsed: 29:11

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1126/1716 | Elapsed: 29:15

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1127/1716 | Elapsed: 29:18

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1128/1716 | Elapsed: 29:22

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1129/1716 | Elapsed: 29:26

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1130/1716 | Elapsed: 29:29

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1131/1716 | Elapsed: 29:32

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1132/1716 | Elapsed: 29:36

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1133/1716 | Elapsed: 29:39

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1134/1716 | Elapsed: 29:43

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1135/1716 | Elapsed: 29:47

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1136/1716 | Elapsed: 29:50

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1137/1716 | Elapsed: 29:54

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1138/1716 | Elapsed: 29:57

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1139/1716 | Elapsed: 30:01

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1140/1716 | Elapsed: 30:04

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1141/1716 | Elapsed: 30:08

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1142/1716 | Elapsed: 30:11

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1143/1716 | Elapsed: 30:16

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1144/1716 | Elapsed: 30:20

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1145/1716 | Elapsed: 30:23

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1146/1716 | Elapsed: 30:26

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1147/1716 | Elapsed: 30:30

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1148/1716 | Elapsed: 30:34

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1149/1716 | Elapsed: 30:38

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1150/1716 | Elapsed: 30:41

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1151/1716 | Elapsed: 30:44

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1152/1716 | Elapsed: 30:48

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1153/1716 | Elapsed: 30:52

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1154/1716 | Elapsed: 30:55

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1155/1716 | Elapsed: 30:59

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1156/1716 | Elapsed: 31:03

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1157/1716 | Elapsed: 31:07

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1158/1716 | Elapsed: 31:10

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1159/1716 | Elapsed: 31:14

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1160/1716 | Elapsed: 31:17

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1161/1716 | Elapsed: 31:21

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1162/1716 | Elapsed: 31:25

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1163/1716 | Elapsed: 31:29

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1164/1716 | Elapsed: 31:33

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1165/1716 | Elapsed: 31:36

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1166/1716 | Elapsed: 31:40

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1167/1716 | Elapsed: 31:43

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1168/1716 | Elapsed: 31:47

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1169/1716 | Elapsed: 31:50

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1170/1716 | Elapsed: 31:55

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1171/1716 | Elapsed: 31:59

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1172/1716 | Elapsed: 32:02

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1173/1716 | Elapsed: 32:06

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1174/1716 | Elapsed: 32:09

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1175/1716 | Elapsed: 32:13

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1176/1716 | Elapsed: 32:17

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1177/1716 | Elapsed: 32:21

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1178/1716 | Elapsed: 32:25

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1179/1716 | Elapsed: 32:28

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1180/1716 | Elapsed: 32:32

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1181/1716 | Elapsed: 32:35

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1182/1716 | Elapsed: 32:39

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1183/1716 | Elapsed: 32:43

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1184/1716 | Elapsed: 32:48

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1185/1716 | Elapsed: 32:52

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1186/1716 | Elapsed: 32:55

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1187/1716 | Elapsed: 32:59

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1188/1716 | Elapsed: 33:03

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1189/1716 | Elapsed: 33:07

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1190/1716 | Elapsed: 33:11

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1191/1716 | Elapsed: 33:15

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1192/1716 | Elapsed: 33:19

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1193/1716 | Elapsed: 33:22

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1194/1716 | Elapsed: 33:26

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1195/1716 | Elapsed: 33:30

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1196/1716 | Elapsed: 33:34

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1197/1716 | Elapsed: 33:38

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1198/1716 | Elapsed: 33:42

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1199/1716 | Elapsed: 33:46

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1200/1716 | Elapsed: 33:50

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1201/1716 | Elapsed: 33:54

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1202/1716 | Elapsed: 33:58

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1203/1716 | Elapsed: 34:01

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1204/1716 | Elapsed: 34:06

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1205/1716 | Elapsed: 34:10

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1206/1716 | Elapsed: 34:13

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1207/1716 | Elapsed: 34:17

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1208/1716 | Elapsed: 34:21

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1209/1716 | Elapsed: 34:24

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1210/1716 | Elapsed: 34:28

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1211/1716 | Elapsed: 34:33

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1212/1716 | Elapsed: 34:36

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1213/1716 | Elapsed: 34:40

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1214/1716 | Elapsed: 34:44

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1215/1716 | Elapsed: 34:47

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1216/1716 | Elapsed: 34:50

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1217/1716 | Elapsed: 34:54

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1218/1716 | Elapsed: 34:58

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1219/1716 | Elapsed: 35:02

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1220/1716 | Elapsed: 35:06

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1221/1716 | Elapsed: 35:10

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1222/1716 | Elapsed: 35:14

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1223/1716 | Elapsed: 35:18

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1224/1716 | Elapsed: 35:23

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1225/1716 | Elapsed: 35:27

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1226/1716 | Elapsed: 35:31

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1227/1716 | Elapsed: 35:35

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1228/1716 | Elapsed: 35:39

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1229/1716 | Elapsed: 35:43

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1230/1716 | Elapsed: 35:47

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1231/1716 | Elapsed: 35:51

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1232/1716 | Elapsed: 35:56

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1233/1716 | Elapsed: 36:00

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1234/1716 | Elapsed: 36:04

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1235/1716 | Elapsed: 36:08

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1236/1716 | Elapsed: 36:12

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1237/1716 | Elapsed: 36:16

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1238/1716 | Elapsed: 36:21

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1239/1716 | Elapsed: 36:25

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1240/1716 | Elapsed: 36:29

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1241/1716 | Elapsed: 36:32

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1242/1716 | Elapsed: 36:36

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1243/1716 | Elapsed: 36:40

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1244/1716 | Elapsed: 36:44

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1245/1716 | Elapsed: 36:49

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1246/1716 | Elapsed: 36:53

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1247/1716 | Elapsed: 36:57

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1248/1716 | Elapsed: 37:03

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1249/1716 | Elapsed: 37:07

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1250/1716 | Elapsed: 37:10

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1251/1716 | Elapsed: 37:16

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1252/1716 | Elapsed: 37:20

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1253/1716 | Elapsed: 37:24

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1254/1716 | Elapsed: 37:28

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1255/1716 | Elapsed: 37:32

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1256/1716 | Elapsed: 37:36

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1257/1716 | Elapsed: 37:41

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1258/1716 | Elapsed: 37:45

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1259/1716 | Elapsed: 37:50

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1260/1716 | Elapsed: 37:54

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1261/1716 | Elapsed: 37:58

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1262/1716 | Elapsed: 38:02

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1263/1716 | Elapsed: 38:06

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1264/1716 | Elapsed: 38:10

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1265/1716 | Elapsed: 38:15

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1266/1716 | Elapsed: 38:19

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1267/1716 | Elapsed: 38:23

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1268/1716 | Elapsed: 38:27

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1269/1716 | Elapsed: 38:31

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1270/1716 | Elapsed: 38:35

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1271/1716 | Elapsed: 38:39

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1272/1716 | Elapsed: 38:44

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1273/1716 | Elapsed: 38:48

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1274/1716 | Elapsed: 38:52

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1275/1716 | Elapsed: 38:56

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1276/1716 | Elapsed: 39:00

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1277/1716 | Elapsed: 39:05

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1278/1716 | Elapsed: 39:09

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1279/1716 | Elapsed: 39:14

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1280/1716 | Elapsed: 39:18

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1281/1716 | Elapsed: 39:22

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1282/1716 | Elapsed: 39:26

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1283/1716 | Elapsed: 39:32

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1284/1716 | Elapsed: 39:36

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1285/1716 | Elapsed: 39:40

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1286/1716 | Elapsed: 39:46

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1287/1716 | Elapsed: 39:50

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1288/1716 | Elapsed: 39:54

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1289/1716 | Elapsed: 39:58

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1290/1716 | Elapsed: 40:02

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1291/1716 | Elapsed: 40:06

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1292/1716 | Elapsed: 40:11

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1293/1716 | Elapsed: 40:17

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1294/1716 | Elapsed: 40:21

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1295/1716 | Elapsed: 40:26

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1296/1716 | Elapsed: 40:30

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1297/1716 | Elapsed: 40:35

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1298/1716 | Elapsed: 40:39

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1299/1716 | Elapsed: 40:44

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1300/1716 | Elapsed: 40:49

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1301/1716 | Elapsed: 40:53

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1302/1716 | Elapsed: 40:57

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1303/1716 | Elapsed: 41:01

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1304/1716 | Elapsed: 41:06

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1305/1716 | Elapsed: 41:11

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1306/1716 | Elapsed: 41:15

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1307/1716 | Elapsed: 41:20

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1308/1716 | Elapsed: 41:25

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1309/1716 | Elapsed: 41:29

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1310/1716 | Elapsed: 41:33

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1311/1716 | Elapsed: 41:37

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1312/1716 | Elapsed: 41:42

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1313/1716 | Elapsed: 41:47

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1314/1716 | Elapsed: 41:52

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1315/1716 | Elapsed: 41:56

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1316/1716 | Elapsed: 42:01

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1317/1716 | Elapsed: 42:05

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1318/1716 | Elapsed: 42:10

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1319/1716 | Elapsed: 42:15

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1320/1716 | Elapsed: 42:19

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1321/1716 | Elapsed: 42:25

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1322/1716 | Elapsed: 42:30

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1323/1716 | Elapsed: 42:34

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1324/1716 | Elapsed: 42:39

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1325/1716 | Elapsed: 42:43

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1326/1716 | Elapsed: 42:48

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1327/1716 | Elapsed: 42:53

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1328/1716 | Elapsed: 42:58

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1329/1716 | Elapsed: 43:03

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1330/1716 | Elapsed: 43:07

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1331/1716 | Elapsed: 43:12

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1332/1716 | Elapsed: 43:16

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1333/1716 | Elapsed: 43:21

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1334/1716 | Elapsed: 43:26

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1335/1716 | Elapsed: 43:32

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1336/1716 | Elapsed: 43:36

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1337/1716 | Elapsed: 43:41

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1338/1716 | Elapsed: 43:45

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1339/1716 | Elapsed: 43:51

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1340/1716 | Elapsed: 43:56

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1341/1716 | Elapsed: 44:01

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1342/1716 | Elapsed: 44:06

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1343/1716 | Elapsed: 44:10

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1344/1716 | Elapsed: 44:15

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1345/1716 | Elapsed: 44:19

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1346/1716 | Elapsed: 44:24

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1347/1716 | Elapsed: 44:28

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1348/1716 | Elapsed: 44:33

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1349/1716 | Elapsed: 44:39

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1350/1716 | Elapsed: 44:43

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1351/1716 | Elapsed: 44:48

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1352/1716 | Elapsed: 44:53

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1353/1716 | Elapsed: 44:58

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1354/1716 | Elapsed: 45:03

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1355/1716 | Elapsed: 45:07

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1356/1716 | Elapsed: 45:14

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1357/1716 | Elapsed: 45:18

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1358/1716 | Elapsed: 45:23

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1359/1716 | Elapsed: 45:28

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1360/1716 | Elapsed: 45:32

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1361/1716 | Elapsed: 45:38

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1362/1716 | Elapsed: 45:43

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1363/1716 | Elapsed: 45:49

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1364/1716 | Elapsed: 45:53

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1365/1716 | Elapsed: 45:58

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1366/1716 | Elapsed: 46:03

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1367/1716 | Elapsed: 46:08

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1368/1716 | Elapsed: 46:14

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1369/1716 | Elapsed: 46:19

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1370/1716 | Elapsed: 46:24

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1371/1716 | Elapsed: 46:29

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1372/1716 | Elapsed: 46:33

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1373/1716 | Elapsed: 46:38

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1374/1716 | Elapsed: 46:44

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1375/1716 | Elapsed: 46:49

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1376/1716 | Elapsed: 46:54

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1377/1716 | Elapsed: 47:00

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1378/1716 | Elapsed: 47:05

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1379/1716 | Elapsed: 47:10

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1380/1716 | Elapsed: 47:14

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1381/1716 | Elapsed: 47:19

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1382/1716 | Elapsed: 47:24

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1383/1716 | Elapsed: 47:28

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1384/1716 | Elapsed: 47:34

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1385/1716 | Elapsed: 47:38

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1386/1716 | Elapsed: 47:43

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1387/1716 | Elapsed: 47:47

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1388/1716 | Elapsed: 47:52

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1389/1716 | Elapsed: 47:57

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1390/1716 | Elapsed: 48:02

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1391/1716 | Elapsed: 48:08

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1392/1716 | Elapsed: 48:13

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1393/1716 | Elapsed: 48:17

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1394/1716 | Elapsed: 48:22

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1395/1716 | Elapsed: 48:27

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1396/1716 | Elapsed: 48:32

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1397/1716 | Elapsed: 48:37

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1398/1716 | Elapsed: 48:42

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1399/1716 | Elapsed: 48:49

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1400/1716 | Elapsed: 48:53

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1401/1716 | Elapsed: 48:58

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1402/1716 | Elapsed: 49:03

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1403/1716 | Elapsed: 49:09

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1404/1716 | Elapsed: 49:14

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1405/1716 | Elapsed: 49:19

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1406/1716 | Elapsed: 49:24

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1407/1716 | Elapsed: 49:29

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1408/1716 | Elapsed: 49:33

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1409/1716 | Elapsed: 49:39

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1410/1716 | Elapsed: 49:45

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1411/1716 | Elapsed: 49:49

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1412/1716 | Elapsed: 49:55

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1413/1716 | Elapsed: 49:59

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1414/1716 | Elapsed: 50:05

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1415/1716 | Elapsed: 50:10

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1416/1716 | Elapsed: 50:15

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1417/1716 | Elapsed: 50:19

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1418/1716 | Elapsed: 50:25

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1419/1716 | Elapsed: 50:31

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1420/1716 | Elapsed: 50:36

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1421/1716 | Elapsed: 50:41

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1422/1716 | Elapsed: 50:47

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1423/1716 | Elapsed: 50:51

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1424/1716 | Elapsed: 50:56

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1425/1716 | Elapsed: 51:01

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1426/1716 | Elapsed: 51:07

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1427/1716 | Elapsed: 51:11

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1428/1716 | Elapsed: 51:16

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1429/1716 | Elapsed: 51:21

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1430/1716 | Elapsed: 51:26

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1431/1716 | Elapsed: 51:31

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1432/1716 | Elapsed: 51:35

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1433/1716 | Elapsed: 51:41

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1434/1716 | Elapsed: 51:46

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1435/1716 | Elapsed: 51:51

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1436/1716 | Elapsed: 51:56

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1437/1716 | Elapsed: 52:01

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1438/1716 | Elapsed: 52:06

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1439/1716 | Elapsed: 52:12

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1440/1716 | Elapsed: 52:16

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1441/1716 | Elapsed: 52:21

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1442/1716 | Elapsed: 52:26

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1443/1716 | Elapsed: 52:30

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1444/1716 | Elapsed: 52:37

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1445/1716 | Elapsed: 52:42

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1446/1716 | Elapsed: 52:47

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1447/1716 | Elapsed: 52:52

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1448/1716 | Elapsed: 52:57

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1449/1716 | Elapsed: 53:02

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1450/1716 | Elapsed: 53:07

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1451/1716 | Elapsed: 53:13

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1452/1716 | Elapsed: 53:19

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1453/1716 | Elapsed: 53:24

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1454/1716 | Elapsed: 53:29

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1455/1716 | Elapsed: 53:35

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1456/1716 | Elapsed: 53:40

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1457/1716 | Elapsed: 53:46

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1458/1716 | Elapsed: 53:52

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1459/1716 | Elapsed: 53:58

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1460/1716 | Elapsed: 54:02

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1461/1716 | Elapsed: 54:08

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1462/1716 | Elapsed: 54:13

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1463/1716 | Elapsed: 54:19

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1464/1716 | Elapsed: 54:25

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1465/1716 | Elapsed: 54:30

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1466/1716 | Elapsed: 54:37

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1467/1716 | Elapsed: 54:42

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1468/1716 | Elapsed: 54:47

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1469/1716 | Elapsed: 54:52

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1470/1716 | Elapsed: 54:57

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1471/1716 | Elapsed: 55:02

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1472/1716 | Elapsed: 55:07

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1473/1716 | Elapsed: 55:14

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1474/1716 | Elapsed: 55:19

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1475/1716 | Elapsed: 55:25

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1476/1716 | Elapsed: 55:30

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1477/1716 | Elapsed: 55:35

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1478/1716 | Elapsed: 55:40

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1479/1716 | Elapsed: 55:48

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1480/1716 | Elapsed: 55:52

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1481/1716 | Elapsed: 55:58

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1482/1716 | Elapsed: 56:02

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1483/1716 | Elapsed: 56:08

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1484/1716 | Elapsed: 56:13

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1485/1716 | Elapsed: 56:19

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1486/1716 | Elapsed: 56:25

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1487/1716 | Elapsed: 56:30

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1488/1716 | Elapsed: 56:35

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1489/1716 | Elapsed: 56:40

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1490/1716 | Elapsed: 56:46

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1491/1716 | Elapsed: 56:52

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1492/1716 | Elapsed: 56:59

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1493/1716 | Elapsed: 57:04

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1494/1716 | Elapsed: 57:09

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1495/1716 | Elapsed: 57:16

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1496/1716 | Elapsed: 57:21

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1497/1716 | Elapsed: 57:26

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1498/1716 | Elapsed: 57:32

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1499/1716 | Elapsed: 57:39

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1500/1716 | Elapsed: 57:43

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1501/1716 | Elapsed: 57:49

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1502/1716 | Elapsed: 57:55

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1503/1716 | Elapsed: 58:00

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1504/1716 | Elapsed: 58:05

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1505/1716 | Elapsed: 58:11

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1506/1716 | Elapsed: 58:18

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1507/1716 | Elapsed: 58:23

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1508/1716 | Elapsed: 58:29

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1509/1716 | Elapsed: 58:35

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1510/1716 | Elapsed: 58:40

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1511/1716 | Elapsed: 58:45

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1512/1716 | Elapsed: 58:50

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1513/1716 | Elapsed: 58:56

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1514/1716 | Elapsed: 59:01

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1515/1716 | Elapsed: 59:06

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1516/1716 | Elapsed: 59:11

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1517/1716 | Elapsed: 59:16

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1518/1716 | Elapsed: 59:22

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1519/1716 | Elapsed: 59:26

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1520/1716 | Elapsed: 59:33

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1521/1716 | Elapsed: 59:39

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1522/1716 | Elapsed: 59:44

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1523/1716 | Elapsed: 59:50

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1524/1716 | Elapsed: 59:55

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1525/1716 | Elapsed: 01:00:01

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1526/1716 | Elapsed: 01:00:07

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1527/1716 | Elapsed: 01:00:13

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1528/1716 | Elapsed: 01:00:18

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1529/1716 | Elapsed: 01:00:23

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1530/1716 | Elapsed: 01:00:28

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1531/1716 | Elapsed: 01:00:34

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1532/1716 | Elapsed: 01:00:39

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1533/1716 | Elapsed: 01:00:46

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1534/1716 | Elapsed: 01:00:53

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1535/1716 | Elapsed: 01:00:58

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1536/1716 | Elapsed: 01:01:03

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1537/1716 | Elapsed: 01:01:10

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1538/1716 | Elapsed: 01:01:15

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1539/1716 | Elapsed: 01:01:20

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1540/1716 | Elapsed: 01:01:27

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1541/1716 | Elapsed: 01:01:33

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1542/1716 | Elapsed: 01:01:39

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1543/1716 | Elapsed: 01:01:44

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1544/1716 | Elapsed: 01:01:49

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1545/1716 | Elapsed: 01:01:55

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1546/1716 | Elapsed: 01:02:01

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1547/1716 | Elapsed: 01:02:07

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1548/1716 | Elapsed: 01:02:14

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1549/1716 | Elapsed: 01:02:19

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1550/1716 | Elapsed: 01:02:25

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1551/1716 | Elapsed: 01:02:30

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1552/1716 | Elapsed: 01:02:36

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1553/1716 | Elapsed: 01:02:43

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1554/1716 | Elapsed: 01:02:50

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1555/1716 | Elapsed: 01:02:55

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1556/1716 | Elapsed: 01:03:01

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1557/1716 | Elapsed: 01:03:07

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1558/1716 | Elapsed: 01:03:12

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1559/1716 | Elapsed: 01:03:19

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1560/1716 | Elapsed: 01:03:25

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1561/1716 | Elapsed: 01:03:32

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1562/1716 | Elapsed: 01:03:37

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1563/1716 | Elapsed: 01:03:44

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1564/1716 | Elapsed: 01:03:50

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1565/1716 | Elapsed: 01:03:56

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1566/1716 | Elapsed: 01:04:02

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1567/1716 | Elapsed: 01:04:09

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1568/1716 | Elapsed: 01:04:16

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1569/1716 | Elapsed: 01:04:21

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1570/1716 | Elapsed: 01:04:26

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1571/1716 | Elapsed: 01:04:32

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1572/1716 | Elapsed: 01:04:38

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1573/1716 | Elapsed: 01:04:44

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1574/1716 | Elapsed: 01:04:52

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1575/1716 | Elapsed: 01:04:57

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1576/1716 | Elapsed: 01:05:03

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1577/1716 | Elapsed: 01:05:09

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1578/1716 | Elapsed: 01:05:14

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1579/1716 | Elapsed: 01:05:20

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1580/1716 | Elapsed: 01:05:26

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1581/1716 | Elapsed: 01:05:34

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1582/1716 | Elapsed: 01:05:41

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1583/1716 | Elapsed: 01:05:47

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1584/1716 | Elapsed: 01:05:53

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1585/1716 | Elapsed: 01:05:59

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1586/1716 | Elapsed: 01:06:07

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1587/1716 | Elapsed: 01:06:15

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1588/1716 | Elapsed: 01:06:21

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1589/1716 | Elapsed: 01:06:27

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1590/1716 | Elapsed: 01:06:33

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1591/1716 | Elapsed: 01:06:38

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1592/1716 | Elapsed: 01:06:45

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1593/1716 | Elapsed: 01:06:53

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1594/1716 | Elapsed: 01:06:59

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1595/1716 | Elapsed: 01:07:04

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1596/1716 | Elapsed: 01:07:11

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1597/1716 | Elapsed: 01:07:18

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1598/1716 | Elapsed: 01:07:24

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1599/1716 | Elapsed: 01:07:29

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1600/1716 | Elapsed: 01:07:35

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1601/1716 | Elapsed: 01:07:40

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1602/1716 | Elapsed: 01:07:48

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1603/1716 | Elapsed: 01:07:53

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1604/1716 | Elapsed: 01:07:59

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1605/1716 | Elapsed: 01:08:05

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1606/1716 | Elapsed: 01:08:11

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1607/1716 | Elapsed: 01:08:18

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1608/1716 | Elapsed: 01:08:24

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1609/1716 | Elapsed: 01:08:31

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1610/1716 | Elapsed: 01:08:38

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1611/1716 | Elapsed: 01:08:44

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1612/1716 | Elapsed: 01:08:51

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1613/1716 | Elapsed: 01:08:58

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1614/1716 | Elapsed: 01:09:04

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1615/1716 | Elapsed: 01:09:10

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1616/1716 | Elapsed: 01:09:16

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1617/1716 | Elapsed: 01:09:23

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1618/1716 | Elapsed: 01:09:30

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1619/1716 | Elapsed: 01:09:36

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1620/1716 | Elapsed: 01:09:44

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1621/1716 | Elapsed: 01:09:50

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1622/1716 | Elapsed: 01:09:56

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1623/1716 | Elapsed: 01:10:01

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1624/1716 | Elapsed: 01:10:08

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1625/1716 | Elapsed: 01:10:15

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1626/1716 | Elapsed: 01:10:21

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1627/1716 | Elapsed: 01:10:27

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1628/1716 | Elapsed: 01:10:33

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1629/1716 | Elapsed: 01:10:39

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1630/1716 | Elapsed: 01:10:46

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1631/1716 | Elapsed: 01:10:53

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1632/1716 | Elapsed: 01:11:01

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1633/1716 | Elapsed: 01:11:08

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1634/1716 | Elapsed: 01:11:13

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1635/1716 | Elapsed: 01:11:19

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1636/1716 | Elapsed: 01:11:26

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1637/1716 | Elapsed: 01:11:31

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1638/1716 | Elapsed: 01:11:39

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1639/1716 | Elapsed: 01:11:46

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1640/1716 | Elapsed: 01:11:53

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1641/1716 | Elapsed: 01:11:58

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1642/1716 | Elapsed: 01:12:05

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1643/1716 | Elapsed: 01:12:11

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1644/1716 | Elapsed: 01:12:18

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1645/1716 | Elapsed: 01:12:24

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1646/1716 | Elapsed: 01:12:30

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1647/1716 | Elapsed: 01:12:38

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1648/1716 | Elapsed: 01:12:44

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1649/1716 | Elapsed: 01:12:50

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1650/1716 | Elapsed: 01:12:56

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1651/1716 | Elapsed: 01:13:02

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1652/1716 | Elapsed: 01:13:08

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1653/1716 | Elapsed: 01:13:14

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1654/1716 | Elapsed: 01:13:21

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1655/1716 | Elapsed: 01:13:27

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1656/1716 | Elapsed: 01:13:33

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1657/1716 | Elapsed: 01:13:40

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1658/1716 | Elapsed: 01:13:47

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1659/1716 | Elapsed: 01:13:53

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1660/1716 | Elapsed: 01:13:59

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1661/1716 | Elapsed: 01:14:07

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1662/1716 | Elapsed: 01:14:12

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1663/1716 | Elapsed: 01:14:19

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1664/1716 | Elapsed: 01:14:24

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1665/1716 | Elapsed: 01:14:30

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1666/1716 | Elapsed: 01:14:36

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1667/1716 | Elapsed: 01:14:42

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1668/1716 | Elapsed: 01:14:49

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1669/1716 | Elapsed: 01:14:55

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1670/1716 | Elapsed: 01:15:01

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1671/1716 | Elapsed: 01:15:08

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1672/1716 | Elapsed: 01:15:16

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1673/1716 | Elapsed: 01:15:22

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1674/1716 | Elapsed: 01:15:28

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1675/1716 | Elapsed: 01:15:37

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1676/1716 | Elapsed: 01:15:43

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1677/1716 | Elapsed: 01:15:49

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1678/1716 | Elapsed: 01:15:55

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1679/1716 | Elapsed: 01:16:01

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1680/1716 | Elapsed: 01:16:07

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1681/1716 | Elapsed: 01:16:14

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1682/1716 | Elapsed: 01:16:21

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1683/1716 | Elapsed: 01:16:27

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1684/1716 | Elapsed: 01:16:33

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1685/1716 | Elapsed: 01:16:39

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1686/1716 | Elapsed: 01:16:46

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1687/1716 | Elapsed: 01:16:52

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1688/1716 | Elapsed: 01:17:00

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1689/1716 | Elapsed: 01:17:07

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1690/1716 | Elapsed: 01:17:13

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1691/1716 | Elapsed: 01:17:20

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1692/1716 | Elapsed: 01:17:27

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1693/1716 | Elapsed: 01:17:35

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1694/1716 | Elapsed: 01:17:41

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1695/1716 | Elapsed: 01:17:50

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1696/1716 | Elapsed: 01:17:56

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1697/1716 | Elapsed: 01:18:02

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1698/1716 | Elapsed: 01:18:10

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1699/1716 | Elapsed: 01:18:17

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1700/1716 | Elapsed: 01:18:23

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1701/1716 | Elapsed: 01:18:30

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1702/1716 | Elapsed: 01:18:37

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1703/1716 | Elapsed: 01:18:44

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1704/1716 | Elapsed: 01:18:50

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1705/1716 | Elapsed: 01:18:57

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1706/1716 | Elapsed: 01:19:03

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1707/1716 | Elapsed: 01:19:10

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1708/1716 | Elapsed: 01:19:16

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1709/1716 | Elapsed: 01:19:23

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1710/1716 | Elapsed: 01:19:29

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1711/1716 | Elapsed: 01:19:35

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1712/1716 | Elapsed: 01:19:42

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1713/1716 | Elapsed: 01:19:49

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1714/1716 | Elapsed: 01:19:56

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1715/1716 | Elapsed: 01:20:04

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanned: 1716/1716 | Elapsed: 01:20:10
Finalizing: Deduplicating DOIs (keeping highest topic scores)...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Done! Unique datasets found: 47,476,822 | Total Time: 82.02 min

In [55]:
con =  duckdb.connect(config["db_path"])
print("\n Dataset Topics")
row_count = con.execute("SELECT count() FROM my_datasets_topics").fetchone()[0]
print(f"Total DOIs in table: {row_count}")
display(con.execute("SELECT * FROM my_datasets_topics ORDER BY pub_date DESC LIMIT 5").df())
con.close()

 Dataset Topics
Total DOIs in table: 47476822

,oa_id,doi,pub_date,topic_id,topic_name,topic_score
0,W4393646606,10.5281/zenodo.8263053,2039-04-01,T11750,Phytoplasmas and Hemiptera pathogens,0.5456
1,W4393614663,10.5281/zenodo.6327222,2036-02-29,T13194,ICT in Developing Communities,0.3324
2,W6949782326,10.5281/zenodo.15473638,2035-05-20,None,None,NaN
3,W6893253683,10.5281/zenodo.15473322,2035-05-20,None,None,NaN
4,W6949459333,10.5281/zenodo.15473196,2035-05-20,None,None,NaN

### Get citations

In [40]:
process_openalex_citations_for_dois(
    db_path=config["db_path"], 
    cite_folder=config["cite_out"],
    meta_folder=config["meta_out"], 
    mem_limit="32GB", 
    temp_dir=config["temp"]
)

Step 1/2: Finding citations in 1716 files...
 > Progress: 1716/1716 | Elapsed: 04:58

Step 2/2: Mapping citing IDs to DOIs and Dates...
Done! Final citation count: 2,754,955 | Total Time: 72.56 min

In [44]:
con =  duckdb.connect(config["db_path"])
print("\n Dataset Citations")
row_count = con.execute("SELECT count() FROM my_datasets_citations").fetchone()[0]
print(f"Total citations in table: {row_count}")
display(con.execute("SELECT * FROM my_datasets_citations LIMIT 5").df())
con.close()

 Dataset Citations
Total citations in table: 2754955

,cited_doi,cited_oa_id,citing_oa_id,citing_doi,citation_date
0,10.4231/qf39-q924,W3215684178,W4399988887,10.1016/j.engfracmech.2024.110257,2024-06-24
1,10.5061/dryad.nvx0k6f46,W6892201352,W4412063596,10.1002/wlb3.01456,2025-07-06
2,10.57702/tuq85ufq,W2953139137,W3011708665,10.1109/iccv48922.2021.00739,2021-10-01
3,10.34894/klajfm,W6909080023,W4393070462,10.1002/wlb3.01237,2024-03-22
4,10.6092/ingv.it-dbmi15,W2773726277,W4293117205,10.5194/nhess-22-2807-2022,2022-08-26

### Add citations weight

In [50]:
create_citation_weights_table(config["db_path"])

Step 3/3: Creating weighted citation table (Defaulting NULL dates to 1.0)...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Success! Table created in 12.38s
Total Citations: 2,754,955
Standard Citations (Weight 1.0): 264,605
Average Impact Score: 1.41

In [54]:
con =  duckdb.connect(config["db_path"])
print("\n Dataset Citations")
row_count = con.execute("SELECT count() FROM my_datasets_citations_weights").fetchone()[0]
print(f"Total citations in table: {row_count}")
display(con.execute("SELECT * FROM my_datasets_citations_weights ORDER BY weight ASC LIMIT 5").df())
con.close()

 Dataset Citations
Total citations in table: 2754955

,cited_doi,cited_oa_id,citing_oa_id,citing_doi,citation_date,pub_date,weight
0,10.14457/cu.the.2006.1939,W2741785518,W2461492322,,2010-01-01,2020-08-03,1.0
1,10.14457/cu.the.2006.1939,W2741785518,W2069232411,10.5539/jmr.v2n2p104,2010-04-19,2020-08-03,1.0
2,10.14457/cu.the.2006.1939,W2741785518,W4247184689,10.5539/jmr.v1n1p0,2009-02-18,2020-08-03,1.0
3,10.14457/cu.the.2006.1939,W2741785518,W1989763262,10.5539/jmr.v1n1p25,2009-02-18,2020-08-03,1.0
4,10.14291/tccon.ggg2014,W6942597812,W4213089580,10.5194/amt-2016-227,2016-08-29,2017-09-13,1.0